### ISSUE TITLE
scripts.pfsense/websafety.sh

### ISSUE THREAD

**Issue by maxmoeller** [diladele/websafety-virtual-appliance#2]
Hi, think little typo

should be fi instead of endif in line 11 and 21

**Comment by ra-at-diladele-com** [comment]
Hello Max, we validate every script by running it on real pfsense. Please note the difference may be because of running it as /bin/tcsh prerequisites.sh (see https://docs.diladele.com/tutorials/filtering_https_traffic_squid_pfsense/diladele.html)
