### ISSUE TITLE
fedora

### ISSUE THREAD

**Issue by erpadmin** [diladele/websafety-virtual-appliance#5]
Would using the CentOS scripts as a basis for a installation on Fedora be feasible?  I spot checked them and believe i use the squid 4.4 repo version w/ecap enabled and the websafety rpm.  I'm sure there will be some issues.  I don't see any modern guides for Fedora out there and that prompted the inquiry.  Also were I successful would the build information be useful to PR for this repo?

Thanks for any information

**Comment by ra-at-diladele-com** [comment]
Hello erpadmin, sorry we do not test on Fedora. It seems to be rapidly changing to keep up with the releases. You can try of course to see if CentOS scripts will work after adjustments.
